generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aPoll
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_poll
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:
        #display: [question]
      edit:    ~
      new:     ~
